# Google Cloud Build configuration for HashR release
steps:
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "build",
        "-t",
        "us-docker.pkg.dev/osdfir-registry/hashr/release/hashr:$TAG_NAME",
        "-t",
        "us-docker.pkg.dev/osdfir-registry/hashr/release/hashr:latest",
        "-f",
        "docker/Dockerfile",
        ".",
      ]
    timeout: 4800s
timeout: 4800s
images:
  - us-docker.pkg.dev/osdfir-registry/hashr/release/hashr:latest
  - us-docker.pkg.dev/osdfir-registry/hashr/release/hashr:$TAG_NAME
